version: '3.7'

volumes:
  postgres:

services:
  vetlab-test:
    container_name: vetlab_test
    image: vetlabtest:latest
    links:
      - postgres
    command: ["--", "-dbHost=postgres"]
  postgres:
    container_name: vetlab_postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
