version: '3.7'

volumes:
  postgres:

services:
  vetlab-api:
    container_name: vetlab_api
    image: vetlab:latest
    ports:
      - "8080:8080"
    links:
      - postgres
    command: [-dbHost=postgres]
  postgres:
    container_name: vetlab_postgres
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
