// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"sync"

	"github.com/jmelchio/vetlab/model"
	"github.com/jmelchio/vetlab/service"
)

type FakeCustomerRepo struct {
	CreateStub        func(*model.Customer) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 *model.Customer
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteStub        func(*model.Customer) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 *model.Customer
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	GetByIDStub        func(uint) (*model.Customer, error)
	getByIDMutex       sync.RWMutex
	getByIDArgsForCall []struct {
		arg1 uint
	}
	getByIDReturns struct {
		result1 *model.Customer
		result2 error
	}
	getByIDReturnsOnCall map[int]struct {
		result1 *model.Customer
		result2 error
	}
	GetByUserNameStub        func(string) (*model.Customer, error)
	getByUserNameMutex       sync.RWMutex
	getByUserNameArgsForCall []struct {
		arg1 string
	}
	getByUserNameReturns struct {
		result1 *model.Customer
		result2 error
	}
	getByUserNameReturnsOnCall map[int]struct {
		result1 *model.Customer
		result2 error
	}
	GetByVetOrgIDStub        func(uint) ([]model.Customer, error)
	getByVetOrgIDMutex       sync.RWMutex
	getByVetOrgIDArgsForCall []struct {
		arg1 uint
	}
	getByVetOrgIDReturns struct {
		result1 []model.Customer
		result2 error
	}
	getByVetOrgIDReturnsOnCall map[int]struct {
		result1 []model.Customer
		result2 error
	}
	UpdateStub        func(*model.Customer) error
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 *model.Customer
	}
	updateReturns struct {
		result1 error
	}
	updateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCustomerRepo) Create(arg1 *model.Customer) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 *model.Customer
	}{arg1})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCustomerRepo) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeCustomerRepo) CreateCalls(stub func(*model.Customer) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeCustomerRepo) CreateArgsForCall(i int) *model.Customer {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCustomerRepo) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepo) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepo) Delete(arg1 *model.Customer) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 *model.Customer
	}{arg1})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCustomerRepo) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeCustomerRepo) DeleteCalls(stub func(*model.Customer) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeCustomerRepo) DeleteArgsForCall(i int) *model.Customer {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCustomerRepo) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepo) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepo) GetByID(arg1 uint) (*model.Customer, error) {
	fake.getByIDMutex.Lock()
	ret, specificReturn := fake.getByIDReturnsOnCall[len(fake.getByIDArgsForCall)]
	fake.getByIDArgsForCall = append(fake.getByIDArgsForCall, struct {
		arg1 uint
	}{arg1})
	stub := fake.GetByIDStub
	fakeReturns := fake.getByIDReturns
	fake.recordInvocation("GetByID", []interface{}{arg1})
	fake.getByIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCustomerRepo) GetByIDCallCount() int {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	return len(fake.getByIDArgsForCall)
}

func (fake *FakeCustomerRepo) GetByIDCalls(stub func(uint) (*model.Customer, error)) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = stub
}

func (fake *FakeCustomerRepo) GetByIDArgsForCall(i int) uint {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	argsForCall := fake.getByIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCustomerRepo) GetByIDReturns(result1 *model.Customer, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	fake.getByIDReturns = struct {
		result1 *model.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepo) GetByIDReturnsOnCall(i int, result1 *model.Customer, result2 error) {
	fake.getByIDMutex.Lock()
	defer fake.getByIDMutex.Unlock()
	fake.GetByIDStub = nil
	if fake.getByIDReturnsOnCall == nil {
		fake.getByIDReturnsOnCall = make(map[int]struct {
			result1 *model.Customer
			result2 error
		})
	}
	fake.getByIDReturnsOnCall[i] = struct {
		result1 *model.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepo) GetByUserName(arg1 string) (*model.Customer, error) {
	fake.getByUserNameMutex.Lock()
	ret, specificReturn := fake.getByUserNameReturnsOnCall[len(fake.getByUserNameArgsForCall)]
	fake.getByUserNameArgsForCall = append(fake.getByUserNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetByUserNameStub
	fakeReturns := fake.getByUserNameReturns
	fake.recordInvocation("GetByUserName", []interface{}{arg1})
	fake.getByUserNameMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCustomerRepo) GetByUserNameCallCount() int {
	fake.getByUserNameMutex.RLock()
	defer fake.getByUserNameMutex.RUnlock()
	return len(fake.getByUserNameArgsForCall)
}

func (fake *FakeCustomerRepo) GetByUserNameCalls(stub func(string) (*model.Customer, error)) {
	fake.getByUserNameMutex.Lock()
	defer fake.getByUserNameMutex.Unlock()
	fake.GetByUserNameStub = stub
}

func (fake *FakeCustomerRepo) GetByUserNameArgsForCall(i int) string {
	fake.getByUserNameMutex.RLock()
	defer fake.getByUserNameMutex.RUnlock()
	argsForCall := fake.getByUserNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCustomerRepo) GetByUserNameReturns(result1 *model.Customer, result2 error) {
	fake.getByUserNameMutex.Lock()
	defer fake.getByUserNameMutex.Unlock()
	fake.GetByUserNameStub = nil
	fake.getByUserNameReturns = struct {
		result1 *model.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepo) GetByUserNameReturnsOnCall(i int, result1 *model.Customer, result2 error) {
	fake.getByUserNameMutex.Lock()
	defer fake.getByUserNameMutex.Unlock()
	fake.GetByUserNameStub = nil
	if fake.getByUserNameReturnsOnCall == nil {
		fake.getByUserNameReturnsOnCall = make(map[int]struct {
			result1 *model.Customer
			result2 error
		})
	}
	fake.getByUserNameReturnsOnCall[i] = struct {
		result1 *model.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepo) GetByVetOrgID(arg1 uint) ([]model.Customer, error) {
	fake.getByVetOrgIDMutex.Lock()
	ret, specificReturn := fake.getByVetOrgIDReturnsOnCall[len(fake.getByVetOrgIDArgsForCall)]
	fake.getByVetOrgIDArgsForCall = append(fake.getByVetOrgIDArgsForCall, struct {
		arg1 uint
	}{arg1})
	stub := fake.GetByVetOrgIDStub
	fakeReturns := fake.getByVetOrgIDReturns
	fake.recordInvocation("GetByVetOrgID", []interface{}{arg1})
	fake.getByVetOrgIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeCustomerRepo) GetByVetOrgIDCallCount() int {
	fake.getByVetOrgIDMutex.RLock()
	defer fake.getByVetOrgIDMutex.RUnlock()
	return len(fake.getByVetOrgIDArgsForCall)
}

func (fake *FakeCustomerRepo) GetByVetOrgIDCalls(stub func(uint) ([]model.Customer, error)) {
	fake.getByVetOrgIDMutex.Lock()
	defer fake.getByVetOrgIDMutex.Unlock()
	fake.GetByVetOrgIDStub = stub
}

func (fake *FakeCustomerRepo) GetByVetOrgIDArgsForCall(i int) uint {
	fake.getByVetOrgIDMutex.RLock()
	defer fake.getByVetOrgIDMutex.RUnlock()
	argsForCall := fake.getByVetOrgIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCustomerRepo) GetByVetOrgIDReturns(result1 []model.Customer, result2 error) {
	fake.getByVetOrgIDMutex.Lock()
	defer fake.getByVetOrgIDMutex.Unlock()
	fake.GetByVetOrgIDStub = nil
	fake.getByVetOrgIDReturns = struct {
		result1 []model.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepo) GetByVetOrgIDReturnsOnCall(i int, result1 []model.Customer, result2 error) {
	fake.getByVetOrgIDMutex.Lock()
	defer fake.getByVetOrgIDMutex.Unlock()
	fake.GetByVetOrgIDStub = nil
	if fake.getByVetOrgIDReturnsOnCall == nil {
		fake.getByVetOrgIDReturnsOnCall = make(map[int]struct {
			result1 []model.Customer
			result2 error
		})
	}
	fake.getByVetOrgIDReturnsOnCall[i] = struct {
		result1 []model.Customer
		result2 error
	}{result1, result2}
}

func (fake *FakeCustomerRepo) Update(arg1 *model.Customer) error {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 *model.Customer
	}{arg1})
	stub := fake.UpdateStub
	fakeReturns := fake.updateReturns
	fake.recordInvocation("Update", []interface{}{arg1})
	fake.updateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCustomerRepo) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeCustomerRepo) UpdateCalls(stub func(*model.Customer) error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = stub
}

func (fake *FakeCustomerRepo) UpdateArgsForCall(i int) *model.Customer {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	argsForCall := fake.updateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeCustomerRepo) UpdateReturns(result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepo) UpdateReturnsOnCall(i int, result1 error) {
	fake.updateMutex.Lock()
	defer fake.updateMutex.Unlock()
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCustomerRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	fake.getByUserNameMutex.RLock()
	defer fake.getByUserNameMutex.RUnlock()
	fake.getByVetOrgIDMutex.RLock()
	defer fake.getByVetOrgIDMutex.RUnlock()
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCustomerRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.CustomerRepo = new(FakeCustomerRepo)
