// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"sync"

	"github.com/jmelchio/vetlab/model"
	"github.com/jmelchio/vetlab/service"
)

type FakeVetOrgRepo struct {
	CreateStub        func(model.VetOrg) (*model.VetOrg, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 model.VetOrg
	}
	createReturns struct {
		result1 *model.VetOrg
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 *model.VetOrg
		result2 error
	}
	UpdateStub        func(model.VetOrg) (*model.VetOrg, error)
	updateMutex       sync.RWMutex
	updateArgsForCall []struct {
		arg1 model.VetOrg
	}
	updateReturns struct {
		result1 *model.VetOrg
		result2 error
	}
	updateReturnsOnCall map[int]struct {
		result1 *model.VetOrg
		result2 error
	}
	DeleteStub        func(model.VetOrg) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 model.VetOrg
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	GetByIDStub        func(uint) (*model.VetOrg, error)
	getByIDMutex       sync.RWMutex
	getByIDArgsForCall []struct {
		arg1 uint
	}
	getByIDReturns struct {
		result1 *model.VetOrg
		result2 error
	}
	getByIDReturnsOnCall map[int]struct {
		result1 *model.VetOrg
		result2 error
	}
	GetByNameStub        func(string) ([]model.VetOrg, error)
	getByNameMutex       sync.RWMutex
	getByNameArgsForCall []struct {
		arg1 string
	}
	getByNameReturns struct {
		result1 []model.VetOrg
		result2 error
	}
	getByNameReturnsOnCall map[int]struct {
		result1 []model.VetOrg
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVetOrgRepo) Create(arg1 model.VetOrg) (*model.VetOrg, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 model.VetOrg
	}{arg1})
	fake.recordInvocation("Create", []interface{}{arg1})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createReturns.result1, fake.createReturns.result2
}

func (fake *FakeVetOrgRepo) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeVetOrgRepo) CreateArgsForCall(i int) model.VetOrg {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].arg1
}

func (fake *FakeVetOrgRepo) CreateReturns(result1 *model.VetOrg, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 *model.VetOrg
		result2 error
	}{result1, result2}
}

func (fake *FakeVetOrgRepo) CreateReturnsOnCall(i int, result1 *model.VetOrg, result2 error) {
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 *model.VetOrg
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 *model.VetOrg
		result2 error
	}{result1, result2}
}

func (fake *FakeVetOrgRepo) Update(arg1 model.VetOrg) (*model.VetOrg, error) {
	fake.updateMutex.Lock()
	ret, specificReturn := fake.updateReturnsOnCall[len(fake.updateArgsForCall)]
	fake.updateArgsForCall = append(fake.updateArgsForCall, struct {
		arg1 model.VetOrg
	}{arg1})
	fake.recordInvocation("Update", []interface{}{arg1})
	fake.updateMutex.Unlock()
	if fake.UpdateStub != nil {
		return fake.UpdateStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.updateReturns.result1, fake.updateReturns.result2
}

func (fake *FakeVetOrgRepo) UpdateCallCount() int {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return len(fake.updateArgsForCall)
}

func (fake *FakeVetOrgRepo) UpdateArgsForCall(i int) model.VetOrg {
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	return fake.updateArgsForCall[i].arg1
}

func (fake *FakeVetOrgRepo) UpdateReturns(result1 *model.VetOrg, result2 error) {
	fake.UpdateStub = nil
	fake.updateReturns = struct {
		result1 *model.VetOrg
		result2 error
	}{result1, result2}
}

func (fake *FakeVetOrgRepo) UpdateReturnsOnCall(i int, result1 *model.VetOrg, result2 error) {
	fake.UpdateStub = nil
	if fake.updateReturnsOnCall == nil {
		fake.updateReturnsOnCall = make(map[int]struct {
			result1 *model.VetOrg
			result2 error
		})
	}
	fake.updateReturnsOnCall[i] = struct {
		result1 *model.VetOrg
		result2 error
	}{result1, result2}
}

func (fake *FakeVetOrgRepo) Delete(arg1 model.VetOrg) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 model.VetOrg
	}{arg1})
	fake.recordInvocation("Delete", []interface{}{arg1})
	fake.deleteMutex.Unlock()
	if fake.DeleteStub != nil {
		return fake.DeleteStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.deleteReturns.result1
}

func (fake *FakeVetOrgRepo) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeVetOrgRepo) DeleteArgsForCall(i int) model.VetOrg {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return fake.deleteArgsForCall[i].arg1
}

func (fake *FakeVetOrgRepo) DeleteReturns(result1 error) {
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVetOrgRepo) DeleteReturnsOnCall(i int, result1 error) {
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVetOrgRepo) GetByID(arg1 uint) (*model.VetOrg, error) {
	fake.getByIDMutex.Lock()
	ret, specificReturn := fake.getByIDReturnsOnCall[len(fake.getByIDArgsForCall)]
	fake.getByIDArgsForCall = append(fake.getByIDArgsForCall, struct {
		arg1 uint
	}{arg1})
	fake.recordInvocation("GetByID", []interface{}{arg1})
	fake.getByIDMutex.Unlock()
	if fake.GetByIDStub != nil {
		return fake.GetByIDStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getByIDReturns.result1, fake.getByIDReturns.result2
}

func (fake *FakeVetOrgRepo) GetByIDCallCount() int {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	return len(fake.getByIDArgsForCall)
}

func (fake *FakeVetOrgRepo) GetByIDArgsForCall(i int) uint {
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	return fake.getByIDArgsForCall[i].arg1
}

func (fake *FakeVetOrgRepo) GetByIDReturns(result1 *model.VetOrg, result2 error) {
	fake.GetByIDStub = nil
	fake.getByIDReturns = struct {
		result1 *model.VetOrg
		result2 error
	}{result1, result2}
}

func (fake *FakeVetOrgRepo) GetByIDReturnsOnCall(i int, result1 *model.VetOrg, result2 error) {
	fake.GetByIDStub = nil
	if fake.getByIDReturnsOnCall == nil {
		fake.getByIDReturnsOnCall = make(map[int]struct {
			result1 *model.VetOrg
			result2 error
		})
	}
	fake.getByIDReturnsOnCall[i] = struct {
		result1 *model.VetOrg
		result2 error
	}{result1, result2}
}

func (fake *FakeVetOrgRepo) GetByName(arg1 string) ([]model.VetOrg, error) {
	fake.getByNameMutex.Lock()
	ret, specificReturn := fake.getByNameReturnsOnCall[len(fake.getByNameArgsForCall)]
	fake.getByNameArgsForCall = append(fake.getByNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetByName", []interface{}{arg1})
	fake.getByNameMutex.Unlock()
	if fake.GetByNameStub != nil {
		return fake.GetByNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getByNameReturns.result1, fake.getByNameReturns.result2
}

func (fake *FakeVetOrgRepo) GetByNameCallCount() int {
	fake.getByNameMutex.RLock()
	defer fake.getByNameMutex.RUnlock()
	return len(fake.getByNameArgsForCall)
}

func (fake *FakeVetOrgRepo) GetByNameArgsForCall(i int) string {
	fake.getByNameMutex.RLock()
	defer fake.getByNameMutex.RUnlock()
	return fake.getByNameArgsForCall[i].arg1
}

func (fake *FakeVetOrgRepo) GetByNameReturns(result1 []model.VetOrg, result2 error) {
	fake.GetByNameStub = nil
	fake.getByNameReturns = struct {
		result1 []model.VetOrg
		result2 error
	}{result1, result2}
}

func (fake *FakeVetOrgRepo) GetByNameReturnsOnCall(i int, result1 []model.VetOrg, result2 error) {
	fake.GetByNameStub = nil
	if fake.getByNameReturnsOnCall == nil {
		fake.getByNameReturnsOnCall = make(map[int]struct {
			result1 []model.VetOrg
			result2 error
		})
	}
	fake.getByNameReturnsOnCall[i] = struct {
		result1 []model.VetOrg
		result2 error
	}{result1, result2}
}

func (fake *FakeVetOrgRepo) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	fake.updateMutex.RLock()
	defer fake.updateMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.getByIDMutex.RLock()
	defer fake.getByIDMutex.RUnlock()
	fake.getByNameMutex.RLock()
	defer fake.getByNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVetOrgRepo) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.VetOrgRepo = new(FakeVetOrgRepo)
